export const READ_RESULTMODAL_SUCCESFUL = 'READ_RESULTMODAL_SUCCESFUL';
export const READ_RESULTMODAL_PENDING = 'READ_RESULTMODAL_PENDING';
export const READ_RESULTMODAL_FAILURE = 'READ_RESULTMODAL_FAILURE';